version: "3.8"

services:
  mongo:
    image: mongo
    container_name: syam-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    image: chandrasyam/syam-node-app:latest
    container_name: syam-node-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo-data:
