version: '3'

services:
  nodeapp:
    build: ./node-app
    container_name: node-app
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    container_name: nginx-reverse-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodeapp
